# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nachricht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nachricht_text', models.TextField(verbose_name='Nachrichtentext')),
                ('zeitstempel', models.FloatField()),
                ('EmailAddresse', models.EmailField(max_length=254)),
                ('Showen', models.BooleanField()),
                ('zeitstring', models.CharField(max_length=100)),
            ],
        ),
    ]
