# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailBoxAndWebserverApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresse_Predef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailAddresse', models.EmailField(max_length=254)),
                ('Color_R', models.IntegerField()),
                ('Color_G', models.IntegerField()),
                ('Color_B', models.IntegerField()),
            ],
        ),
    ]
